import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { fakeApiRoot, openPanel, resetE2eState, selectWorkspaceLayout, setWorkspaceMode } from './test-state.js';

test('原文并排、放大和受限区域切换保留草稿、运行及并排栏位', async ({ page, request }, testInfo) => {
  await resetE2eState(request);
  const ids = [crypto.randomUUID(), crypto.randomUUID()];
  for (const [index, sessionId] of ids.entries()) {
    const response = await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId, title: `阅读布局${index}` } });
    const root = (await response.json()).workingDirectory.path as string;
    writeFileSync(join(root, 'notes.txt'), Array.from({ length: 100 }, (_, line) => `第 ${line + 1} 行真实阅读内容`).join('\n'));
  }
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/'); await openPanel(page, 'workspace');
  await selectWorkspaceLayout(page, 2); await setWorkspaceMode(page, 'parallel');
  const panel = page.locator(`.conversation-panel[data-session-id="${ids[0]}"]`);
  const continuing = panel.getByRole('button', { name: '在「阅读布局0」中继续' });
  if (await continuing.isVisible()) await continuing.click();
  await panel.getByLabel('Multivac 草稿').fill('保留阅读草稿');
  const separator = page.getByRole('separator').first();
  await separator.focus(); await separator.press('ArrowRight');
  const widths = await page.locator('.workspace-panels').evaluate((element) => getComputedStyle(element).gridTemplateColumns);
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  const browser = panel.getByRole('region', { name: '工作目录文件浏览' });
  await browser.getByRole('button', { name: 'notes.txt', exact: true }).click();
  await expect(panel.locator('.discussion-surface')).toHaveClass(/has-reading/);
  await expect(panel.getByLabel('Multivac 草稿')).toHaveValue('保留阅读草稿');
  await expect(browser.getByRole('article')).toContainText('真实阅读内容');
  await page.screenshot({ path: testInfo.outputPath('split.png') });
  await browser.getByRole('button', { name: '放大原文' }).click();
  await expect(panel.getByLabel('Multivac 草稿')).toBeHidden();
  await page.screenshot({ path: testInfo.outputPath('original.png') });
  await browser.getByRole('button', { name: '回到当前讨论' }).click();
  await expect(panel.getByLabel('Multivac 草稿')).toBeVisible();
  await page.keyboard.press('ControlOrMeta+J');
  await page.setViewportSize({ width: 900, height: 820 });
  await expect(panel.getByLabel('Multivac 草稿')).toBeHidden();
  await browser.getByRole('button', { name: '回到当前讨论' }).click();
  await expect(panel.getByLabel('Multivac 草稿')).toHaveValue('保留阅读草稿');
  await expect(browser).toBeHidden();
  await page.screenshot({ path: testInfo.outputPath('discussion.png') });
  await panel.getByRole('button', { name: '返回原文' }).click();
  await expect(browser.getByRole('article')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('constrained.png') });
  await browser.getByRole('button', { name: '关闭文件浏览' }).click();
  await expect(panel).toHaveClass(/focused/);
  await expect(panel.getByLabel('Multivac 草稿')).toHaveValue('保留阅读草稿');
  expect((await request.post(`${fakeApiRoot}/api/__e2e/assistant/prompt-completion/arm`)).ok()).toBeTruthy();
  await panel.getByLabel('发送消息').click();
  await expect(panel.getByRole('button', { name: '取消当前处理' })).toBeVisible();
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  await panel.getByRole('button', { name: '返回并排' }).click();
  await expect(browser).toBeHidden();
  await expect(page.locator('.conversation-panel:visible')).toHaveCount(2);
  await page.setViewportSize({ width: 1440, height: 900 });
  const collapse = page.getByRole('button', { name: /^收起 Multivac/ });
  if (await collapse.isVisible()) await collapse.click();
  await expect.poll(() => page.locator('.workspace-panels').evaluate((element) => getComputedStyle(element).gridTemplateColumns)).toBe(widths);
  expect((await request.post(`${fakeApiRoot}/api/__e2e/assistant/prompt-completion/release`)).ok()).toBeTruthy();
  await expect(panel.getByRole('status').getByText('处理完成', { exact: true })).toBeVisible();
});
