import { mkdirSync, writeFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { fakeApiRoot, openPanel, resetE2eState, setWorkspaceMode, workspaceRail } from './test-state.js';

test('阅读历史与纵横滚动、查找、目录展开在关闭、刷新及并排切换后恢复', async ({ page, request }, testInfo) => {
  await resetE2eState(request);
  const sessionId = crypto.randomUUID();
  const response = await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId, title: '阅读现场验收' } });
  const root = (await response.json()).workingDirectory.path as string;
  mkdirSync(join(root, 'docs'));
  writeFileSync(join(root, 'docs', 'long.ts'), Array.from({ length: 200 }, (_, line) => `const line${line} = "${'真实长行原文 '.repeat(30)}";`).join('\n'));
  writeFileSync(join(root, 'next.txt'), '下一份真实文件');
  await page.goto('/'); await openPanel(page, 'workspace');
  const panel = page.locator(`.conversation-panel[data-session-id="${sessionId}"]`);
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  const browser = panel.getByRole('region', { name: '工作目录文件浏览' });
  await browser.getByRole('button', { name: 'docs', exact: true }).click();
  await browser.getByRole('button', { name: 'long.ts', exact: true }).click();
  const article = browser.getByRole('article');
  await expect(article).toContainText('const line0');
  await browser.getByRole('button', { name: '查找原文', exact: true }).click();
  await browser.getByLabel('原文内查找').fill('line10');
  await article.evaluate((element) => { element.scrollTop = 950; element.scrollLeft = 180; element.dispatchEvent(new Event('scroll')); });
  await browser.getByRole('button', { name: 'next.txt', exact: true }).click();
  await expect(article).toContainText('下一份真实文件');
  await browser.getByRole('button', { name: '返回上一处阅读' }).click();
  await expect(article).toContainText('const line0');
  await expect(browser.getByLabel('原文内查找')).toHaveValue('line10');
  await expect.poll(() => article.evaluate((element) => [element.scrollTop, element.scrollLeft])).toEqual([950, 180]);
  await browser.getByRole('button', { name: '前进下一处阅读' }).click();
  await expect(article).toContainText('下一份真实文件');
  await browser.getByRole('button', { name: '返回上一处阅读' }).click();
  await expect(article).toContainText('const line0');
  await browser.getByRole('button', { name: '关闭文件浏览' }).click();
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  await expect.poll(() => article.evaluate((element) => [element.scrollTop, element.scrollLeft])).toEqual([950, 180]);
  await page.reload();
  await openPanel(page, 'workspace');
  await expect(article).toContainText('const line0');
  await expect.poll(() => article.evaluate((element) => [element.scrollTop, element.scrollLeft])).toEqual([950, 180]);
  await expect(browser.getByLabel('原文内查找')).toHaveValue('line10');
  await page.screenshot({ path: testInfo.outputPath('restored.png') });
  await panel.getByRole('button', { name: '返回并排' }).click();
  await setWorkspaceMode(page, 'focus');
  await expect(article).toContainText('const line0');
  await expect.poll(() => article.evaluate((element) => element.scrollTop)).toBe(950);
  await browser.getByRole('button', { name: '选择工作目录文件' }).click();
  await expect(browser.getByRole('heading', { name: '最近查看' })).toBeVisible();
  await expect(browser.locator('.browser-chooser')).toContainText('docs/long.ts');
  await browser.getByRole('button', { name: '返回当前文件' }).click();
  unlinkSync(join(root, 'docs', 'long.ts'));
  await page.reload();
  await openPanel(page, 'workspace');
  await expect(browser.getByRole('alert')).toContainText('不存在');
});

test('最近与真实工作区隔离；损坏记录与归入项目后的同名文件不误恢复', async ({ page, request }) => {
  await resetE2eState(request);
  const sessionId = crypto.randomUUID();
  const created = await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId, title: '隔离阅读现场' } });
  const root = (await created.json()).workingDirectory.path as string;
  writeFileSync(join(root, 'notes.txt'), '旧目录原文');
  await page.goto('/'); await openPanel(page, 'workspace');
  const panel = page.locator(`.conversation-panel[data-session-id="${sessionId}"]`);
  await panel.getByLabel('Multivac 草稿').fill('记录真实活动'); await panel.getByLabel('发送消息').click();
  await expect(panel.getByRole('status').getByText('处理完成', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  const browser = panel.getByRole('region', { name: '工作目录文件浏览' });
  await browser.getByRole('button', { name: 'notes.txt', exact: true }).click();
  await expect(browser.getByRole('article')).toContainText('旧目录原文');
  await workspaceRail(page).locator('.rail-group[data-workspace-id="recent"]').getByRole('button', { name: '隔离阅读现场', exact: true }).click();
  await expect(browser).toBeHidden();
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  await expect(browser.getByRole('heading', { name: '工作目录文件' })).toBeVisible();
  await workspaceRail(page).locator('.rail-group[data-workspace-id="default"]').getByRole('button', { name: '隔离阅读现场', exact: true }).click();
  await expect(browser.getByRole('article')).toContainText('旧目录原文');
  await page.evaluate((id) => localStorage.setItem(`multivac.reading.v1:${JSON.stringify(['default', id])}`, '{broken'), sessionId);
  await page.reload(); await openPanel(page, 'workspace');
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  await expect(browser.getByRole('heading', { name: '工作目录文件' })).toBeVisible();
  const projectResponse = await request.post(`${fakeApiRoot}/api/projects`, { data: { name: '阅读迁移目标' } });
  const project = (await projectResponse.json()).project;
  writeFileSync(join(project.directories[0].path, 'notes.txt'), '新目录同名原文');
  const moved = await request.post(`${fakeApiRoot}/api/sessions/${sessionId}/move-to-project`, { data: { projectId: project.projectId, moveFiles: false } });
  expect(moved.ok()).toBeTruthy();
  const stale = await request.get(`${fakeApiRoot}/api/sessions/${sessionId}/files/content`, { params: { path: 'notes.txt', root } });
  expect(stale.status()).toBe(409);
  await page.reload(); await openPanel(page, 'workspace');
  await workspaceRail(page).locator(`.rail-group[data-workspace-id="${project.projectId}"]`).getByRole('button', { name: '隔离阅读现场', exact: true }).click();
  await panel.getByRole('button', { name: '查看文件', exact: true }).click();
  await expect(browser.getByRole('heading', { name: '工作目录文件' })).toBeVisible();
  await expect(browser).not.toContainText('新目录同名原文');
});
