import { test, expect } from '@playwright/test';
import { fakeApiRoot, resetE2eState, openPanel } from './test-state.js';

test('默认 Agent，明确勾选我来处理后可筛选、切换标记并由用户完成', async ({ page, request }) => {
  await resetE2eState(request);
  await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: 'agent', title: '会议资料整理', goal: '整理议程' } });
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await page.getByRole('button', { name: '新建任务', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '创建任务', exact: true });
  await expect(dialog.getByRole('checkbox', { name: '我来处理', exact: true })).not.toBeChecked();
  await dialog.getByRole('textbox', { name: '任务名称', exact: true }).fill('参加项目评审');
  await dialog.getByRole('textbox', { name: '目标说明', exact: true }).fill('我参加会议并记录结论');
  await dialog.getByRole('checkbox', { name: '我来处理', exact: true }).check();
  await expect(dialog.getByText('完成后需要我验收', { exact: true })).toHaveCount(0);
  await dialog.getByRole('button', { name: '创建任务', exact: true }).click();
  const inspector = page.getByRole('complementary', { name: '任务详情' });
  await expect(inspector).toContainText('由你完成，Agent 不会执行');
  await expect(inspector.getByRole('button', { name: '启动任务：参加项目评审', exact: true })).toHaveCount(0);
  await inspector.getByRole('checkbox', { name: '我来处理', exact: true }).click();
  await expect(inspector.getByRole('button', { name: '启动任务：参加项目评审', exact: true })).toBeVisible();
  await inspector.getByRole('checkbox', { name: '我来处理', exact: true }).click();
  await expect(inspector.getByRole('button', { name: '标记完成：参加项目评审', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '任务处理方式：全部任务', exact: true }).click();
  await page.getByRole('option', { name: '我来处理', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看任务：会议资料整理', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await expect(page.locator('.task-list-row')).toHaveCount(1);
  await expect(page.locator('.task-list-row')).toContainText('我来处理');
  await inspector.getByRole('button', { name: '标记完成：参加项目评审', exact: true }).click();
  await expect(inspector.getByRole('region', { name: '当前情况' })).toContainText('已完成');
  await expect(inspector.getByRole('region', { name: '任务人工请求' })).toHaveCount(0);
  const tasks = (await (await request.get(`${fakeApiRoot}/api/tasks?humanOnly=true`)).json()).tasks;
  expect(tasks).toHaveLength(1);
  const detail = (await (await request.get(`${fakeApiRoot}/api/tasks/${tasks[0].taskId}`)).json());
  expect(detail.runs).toHaveLength(0);
  expect(detail.task.status).toBe('done');
  await page.getByRole('button', { name: '任务处理方式：我来处理', exact: true }).click();
  await page.getByRole('option', { name: 'Agent 处理', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看任务：会议资料整理', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '查看任务：参加项目评审', exact: true })).toHaveCount(0);
});
