import { expect, test, type APIRequestContext, type Page } from '@playwright/test';
import { fakeApiRoot, openPanel, openArchivePage, resetE2eState, ensureWorkspaceRail, selectWorkspace } from './test-state.js';
const archive = (page: Page) => page.getByRole('main', { name: '归档' });
const titles = (page: Page) => archive(page).locator('.archive-list strong');
async function create(request: APIRequestContext, sessionId: string, title: string, workspaceId = 'default', archived = true) {
  expect((await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId, title, workspaceId } })).ok()).toBeTruthy();
  if (archived) expect((await request.post(`${fakeApiRoot}/api/sessions/${sessionId}/archive`)).ok()).toBeTruthy();
}
test.beforeEach(async ({ request }) => { await resetE2eState(request); });

test('设置归档可达，与当前会话导航分开；只含归档并按归档时间排序，搜索及真实工作区筛选', async ({ page, request }) => {
  const project = (await (await request.post(`${fakeApiRoot}/api/projects`, { data: { name: '归档项目' } })).json()).workspace;
  await create(request, 'old', '旧归档');
  await create(request, 'active', '未归档', 'default', false);
  await create(request, 'new', '项目归档', project.workspaceId);
  await page.goto('/'); await openPanel(page, 'management');
  const nav = page.getByRole('complementary', { name: '管理导航' });
  await expect(nav.getByRole('group', { name: '工作' }).getByRole('button', { name: '会话', exact: true })).toBeVisible();
  await expect(nav.getByRole('group', { name: '设置' }).getByRole('button', { name: '归档' })).toBeVisible();
  await nav.getByRole('button', { name: '归档', exact: true }).click();
  await expect(titles(page)).toHaveText(['项目归档', '旧归档']);
  await expect(archive(page).getByRole('group', { name: '按状态筛选' })).toHaveCount(0);
  await expect(archive(page).getByRole('group', { name: '按类型筛选' })).toHaveCount(0);
  await archive(page).getByLabel('按项目筛选').selectOption('default');
  await expect(titles(page)).toHaveText(['旧归档']);
  await archive(page).getByLabel('按项目筛选').selectOption(project.workspaceId);
  await archive(page).getByLabel('按标题搜索').fill('没有');
  await expect(archive(page)).toContainText('没有符合条件的归档');
  await archive(page).getByLabel('按标题搜索').fill('项目');
  await expect(titles(page)).toHaveText(['项目归档']);
  await page.setViewportSize({ width: 1000, height: 900 });
  await page.keyboard.press('ControlOrMeta+J');
  await expect(page.locator('.multivac-sidebar')).toBeVisible();
  await expect.poll(() => archive(page).evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
  const sidebar = page.locator('.multivac-sidebar');
  const turn = page.waitForRequest((item) => item.method() === 'POST' && new URL(item.url()).pathname === '/api/assistant/turns');
  await sidebar.getByLabel('Multivac 草稿').fill('查看当前归档\n内部工具：get_current_view#archive-view {}');
  await sidebar.getByLabel('发送消息').click();
  const sent = (await turn).postDataJSON();
  expect(sent.view.management).toEqual({ page: 'archive', selection: { kind: 'session', sessionId: 'new' } });
  expect(sent.contextRefs ?? []).toEqual([]);
  await expect(sidebar.getByRole('status').getByText('处理完成', { exact: true })).toBeVisible();
  await page.keyboard.press('ControlOrMeta+J');
  await page.keyboard.press('ControlOrMeta+K');
  const palette = page.getByRole('dialog', { name: '跳到页面' });
  await palette.getByRole('combobox').fill('恢复');
  await expect(palette.getByRole('option')).toHaveCount(1);
  await expect(palette.getByRole('option')).toContainText('归档');
  await page.keyboard.press('Enter'); await expect(archive(page)).toBeVisible();
});

test('从管理页筛选归档；重复恢复受保护，恢复后焦点和工作区共享列表同步', async ({ page, request }) => {
  const project = (await (await request.post(`${fakeApiRoot}/api/projects`, { data: { name: '项目甲' } })).json()).workspace;
  await create(request, 'default-old', '默认归档'); await create(request, 'project-old', '项目归档', project.workspaceId);
  await create(request, 'live', '当前会话', 'default', false);
  await page.goto('/'); await openPanel(page, 'workspace'); await ensureWorkspaceRail(page);
  await expect(page.getByRole('complementary', { name: '工作区会话导航' }).getByRole('button', { name: '查看归档' })).toHaveCount(0);
  await openArchivePage(page);
  await archive(page).getByLabel('按项目筛选').selectOption('default');
  await expect(archive(page).getByLabel('按项目筛选')).toHaveValue('default');
  await expect(titles(page)).toHaveText(['默认归档']);
  let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); let calls = 0;
  await page.route('**/sessions/default-old/restore', async (route) => { calls += 1; await gate; await route.continue(); });
  await archive(page).getByRole('button', { name: '恢复', exact: true }).click();
  await expect(archive(page).getByRole('button', { name: '恢复', exact: true })).toBeDisabled();
  release();
  await expect(archive(page)).toContainText('没有符合条件的归档');
  await expect(archive(page).getByLabel('按标题搜索')).toBeFocused(); expect(calls).toBe(1);
  await openPanel(page, 'workspace'); await ensureWorkspaceRail(page);
  await expect(page.locator('.rail-folder.active').locator('..').locator('.rail-item').filter({ hasText: '默认归档' })).toBeVisible();
  await selectWorkspace(page, '最近');
  await openArchivePage(page);
  await archive(page).getByLabel('按项目筛选').selectOption('all');
  await expect(archive(page).getByLabel('按项目筛选')).toHaveValue('all');
  await expect(titles(page)).toHaveText(['项目归档']);
  await archive(page).getByRole('button', { name: '恢复并打开' }).click();
  await expect(page.locator('.rail-folder.active')).toContainText('项目甲');
  await expect(page.locator('.conversation-panel:visible h2')).toHaveText('项目归档');
});

test('无项目隐藏筛选；加载失败可重试，空列表与授权窗口关闭返回焦点', async ({ page, request }) => {
  await create(request, 'one', '归档授权');
  await page.route('**/api/sessions?*', (route) => route.fulfill({ status: 503, json: { error: { code: 'INTERNAL_ERROR', message: '读取失败' } } }));
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '归档', exact: true }).click();
  await expect(archive(page).getByRole('button', { name: '重试' })).toBeVisible();
  await page.unroute('**/api/sessions?*');
  await archive(page).getByRole('button', { name: '重试' }).click();
  await expect(titles(page)).toHaveText(['归档授权']);
  await expect(archive(page).getByLabel('按项目筛选')).toHaveCount(0);
  const trigger = archive(page).getByRole('button', { name: '授权', exact: true });
  await page.route('**/api/authorization-requests?*', (route) => route.fulfill({ status: 503, json: { error: { code: 'INTERNAL_ERROR', message: '历史读取失败' } } }));
  await page.route('**/api/authorization-grants', (route) => route.fulfill({ status: 503, json: { error: { code: 'INTERNAL_ERROR', message: '授权读取失败' } } }));
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: '「归档授权」的授权' });
  const history = dialog.getByRole('region', { name: '最近的授权请求' });
  const grants = dialog.getByRole('region', { name: '本会话已允许' });
  await expect(history.getByRole('alert')).toContainText('历史读取失败');
  await expect(grants.getByRole('alert')).toContainText('授权读取失败');
  await page.unroute('**/api/authorization-requests?*');
  await page.unroute('**/api/authorization-grants');
  await history.getByRole('button', { name: '重试' }).click();
  await grants.getByRole('button', { name: '重试' }).click();
  await expect(history).toContainText('这个会话还没有授权请求');
  await expect(grants).toContainText('这个会话还没有记住的授权');
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0); await expect(trigger).toBeFocused();
  await archive(page).getByRole('button', { name: '恢复', exact: true }).click();
  await expect(archive(page)).toContainText('还没有归档会话');
});
