import { expect, test } from '@playwright/test';
import { openPanel, fakeApiRoot } from './test-state.js';

test('真实书籍从文件导入，切换与刷新读取持久书架', async ({ page, request }, testInfo) => {
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('button', { name: '导入书籍' }).click();
  await page.locator('input[type=file]').setInputFiles({ name: '真实书籍.md', mimeType: 'text/markdown', buffer: Buffer.from('# 第一章\n\n这是从真实文件导入的正文😀。\n\n# 第二章\n\n第二章的内容。') });
  await page.getByLabel('作者', { exact: true }).fill('测试作者');
  await page.getByRole('button', { name: '导入', exact: true }).click();
  await expect(page.locator('.reading-content')).toContainText('这是从真实文件导入的正文😀。');
  const books = await (await request.get(`${fakeApiRoot}/api/reading/books`)).json();
  const book = books.books.find((b: { title: string }) => b.title === '真实书籍');
  expect(book.version).toMatch(/^[a-f0-9]{64}$/u);
  await page.screenshot({ path: testInfo.outputPath('reading-library-desktop.png') });
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /真实书籍/u }).click();
  await expect(page.locator('.reading-content')).toContainText('第二章的内容。');
  const invalid = await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'invalid', format: 'pdf', title: 'pdf', author: '', text: 'data' } });
  expect(invalid.status()).toBe(400);
});

test('书签备注与跨段划线持久化，重新分页后可定位原文', async ({ page, request }, testInfo) => {
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'annotation-book', title: '标注验证', author: '', format: 'md', text: '# 章节\n\n第一段😀正文。\n\n第二段的正文。\n\n# 后文\n\n另一章。' } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /标注验证/u }).click();
  await page.getByRole('button', { name: '当前页书签' }).click();
  await expect(page.getByRole('button', { name: '当前页书签' })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '阅读记录', exact: true }).click();
  await page.getByLabel('书签备注').fill('重读这里'); await page.getByRole('button', { name: '保存备注' }).click();
  await expect(page.getByRole('button', { name: '保存备注' })).toBeDisabled();
  await page.evaluate(() => {
    const paragraphs = document.querySelectorAll('.reading-flow p');
    const a = paragraphs[0]!.firstChild!, b = paragraphs[1]!.firstChild!;
    const range = document.createRange(); range.setStart(a.firstChild!, 0); range.setEnd(b.firstChild!, 3);
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  });
  await page.getByRole('toolbar', { name: '选区操作' }).getByRole('button', { name: '划线', exact: true }).click();
  await expect(page.locator('.reading-flow mark').first()).toBeVisible();
  await page.getByRole('tab', { name: '划线', exact: true }).click();
  await expect(page.locator('.reading-record-panel blockquote')).toHaveText('第一段😀正文。\n第二段');
  await page.screenshot({ path: testInfo.outputPath('reading-annotations-desktop.png') });
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await expect(page.locator('.reading-flow mark').first()).toBeVisible();
  const records = await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/annotations`)).json();
  expect(records.records.find((r: { kind: string }) => r.kind === 'bookmark').remark).toBe('重读这里');
  await page.getByRole('button', { name: '阅读记录', exact: true }).click();
  await page.getByRole('tab', { name: '划线', exact: true }).click();
  await page.getByRole('button', { name: '定位原文', exact: true }).click();
  await expect(page.getByRole('button', { name: '返回阅读处' })).toBeVisible();
  await page.getByRole('button', { name: '移除划线' }).click();
  await expect(page.locator('.reading-flow mark')).toHaveCount(0);
});

test('原生分页无丢字或重叠，字号和宽度变化保留原文锚点', async ({ page, request }, testInfo) => {
  const text = '# 起点\n\n' + '长段落中的文字😀和组合字符e\u0301。'.repeat(300) + '\n\n下一段原文。\n\n# 终点\n\n最后一段。';
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'pagination-book', title: '分页验证', author: '', format: 'md', text } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /分页验证/u }).click();
  await expect(page.getByRole('button', { name: '下一页', exact: true })).toBeEnabled();
  const readScene = () => page.evaluate(id => JSON.parse(localStorage.getItem(`multivac.reading.scene.${id}`)!), book.id);
  await page.getByLabel('页码', { exact: true }).fill('3'); await page.getByRole('button', { name: '跳转', exact: true }).click();
  await expect(page.getByLabel('页码', { exact: true })).toHaveValue('3');
  const original = (await readScene()).position;
  await page.getByRole('button', { name: '字号', exact: true }).click();
  await page.getByRole('slider').fill('26');
  await expect.poll(async () => (await readScene()).fontSize).toBe(26);
  expect((await readScene()).position).toEqual(original);
  await page.getByRole('slider').press('Escape');
  await page.setViewportSize({ width: 1120, height: 760 });
  await expect(page.locator('.reading-flow')).toBeVisible();
  expect((await readScene()).position).toEqual(original);
  const ranges = await page.evaluate(async bookId => {
    const book = await (await fetch(`/api/reading/books/${bookId}`)).json();
    // 在真实 DOM 上调用同一原生布局读取器，验证稳定段落被完整覆盖。
    const modulePath = '/src/features/reading/reading-layout.ts';
    const { measureReadingPages } = await import(modulePath);
    const viewport = document.querySelector('.reading-page-viewport') as HTMLElement;
    return measureReadingPages(book, document.querySelector('.reading-flow'), viewport.clientWidth);
  }, book.id);
  const ps = book.chapters.flatMap((c: { id: string; paragraphs: { id: string; text: string }[] }) => c.paragraphs.map(p => ({ ...p, chapterId: c.id })));
  for (const p of ps) {
    const covered = ranges.filter((r: { start: { paragraphId: string }; end: { paragraphId: string } }) => {
      const a = ps.findIndex((item: { id: string }) => item.id === r.start.paragraphId), b = ps.findIndex((item: { id: string }) => item.id === r.end.paragraphId), i = ps.indexOf(p);
      return a <= i && b >= i;
    }).map((r: { start: { paragraphId: string; offset: number }; end: { paragraphId: string; offset: number } }) => p.text.slice(r.start.paragraphId === p.id ? r.start.offset : 0, r.end.paragraphId === p.id ? r.end.offset : p.text.length)).join('');
    expect(covered).toBe(p.text);
  }
  await page.screenshot({ path: testInfo.outputPath('reading-pagination-desktop.png') });
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await expect(page.locator('.reading-toolbar h2')).toHaveText('分页验证');
  expect((await readScene()).position).toEqual(original);
  await page.getByRole('button', { name: '目录', exact: true }).click();
  await page.getByRole('navigation', { name: '目录' }).getByRole('button', { name: '终点', exact: true }).click();
  await expect(page.locator('.reading-chapter-title')).toContainText('终点');
  await page.getByRole('button', { name: '返回阅读处', exact: true }).click();
  expect((await readScene()).position).toEqual(original);
});

test('书伴复用会话链路，翻页不推进已读范围或自动发送，草稿与来源刷新恢复', async ({ page, request }, testInfo) => {
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'companion-book', title: '共读验证', author: '', format: 'md', text: '# 当前\n\n眼前的原文。\n\n# 未来\n\n尚未阅读的未来内容。' } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /共读验证/u }).click();
  await page.getByRole('button', { name: '书伴', exact: true }).click();
  await expect(page.getByLabel('向书伴提问')).toBeEnabled();
  const session = await (await request.post(`${fakeApiRoot}/api/reading/books/${book.id}/companion`)).json();
  await page.getByRole('button', { name: '下一页', exact: true }).click();
  let scope = await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/scope`)).json();
  expect(scope.boundary).toBeNull();
  const before = await (await request.get(`${fakeApiRoot}/api/sessions/${session.sessionId}/session`)).json();
  expect(before.messages).toHaveLength(0);
  await page.getByRole('button', { name: '上一页', exact: true }).click();
  await page.getByText('讨论范围 ·', { exact: false }).click();
  await page.getByRole('button', { name: '已读到当前页末' }).click();
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/scope`)).json()).revision).toBe(1);
  await page.getByLabel('向书伴提问').fill('解释当前原文'); await page.getByRole('button', { name: '发送给书伴' }).click();
  await expect(page.locator('.reading-messages .reading-message')).toHaveCount(2);
  await page.getByLabel('向书伴提问').fill('尚未发送的草稿');
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/sessions/${session.sessionId}/page-state`)).json()).draft).toBe('尚未发送的草稿');
  await page.screenshot({ path: testInfo.outputPath('reading-companion-desktop.png') });
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await expect(page.getByLabel('向书伴提问')).toHaveValue('尚未发送的草稿');
  await expect(page.locator('.reading-messages .reading-message')).toHaveCount(2);
  await page.getByText('讨论范围 ·', { exact: false }).click();
  await page.getByRole('button', { name: '重置已读范围' }).click();
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/scope`)).json()).boundary).toBeNull();
});

test('笔记草稿刷新恢复，切换原文先处理草稿，保存与修改真实落盘', async ({ page, request }, testInfo) => {
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'notes-book', title: '笔记验证', author: '', format: 'md', text: '# 首章\n\n值得记录的原文。\n\n# 次章\n\n另一处原文。' } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /笔记验证/u }).click();
  await page.getByRole('button', { name: '为当前页写笔记' }).click();
  await page.getByLabel('笔记内容').fill('未保存的阅读想法');
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/notes`)).json()).draft?.body).toBe('未保存的阅读想法');
  let notes = await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/notes`)).json(); expect(notes.notes).toHaveLength(0);
  await page.getByRole('button', { name: '收起笔记，保留草稿' }).click();
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('button', { name: '下一页', exact: true }).click();
  await page.getByRole('button', { name: '为当前页写笔记' }).click();
  await expect(page.getByLabel('笔记内容')).toHaveValue('未保存的阅读想法');
  await expect(page.getByRole('button', { name: '继续原草稿' })).toBeVisible();
  await page.getByRole('button', { name: '保存并继续' }).click();
  await expect(page.getByLabel('笔记内容')).toHaveValue('');
  await page.getByLabel('笔记内容').fill('第二处想法');
  await expect(page.getByRole('button', { name: '保存笔记', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await expect(page.getByLabel('笔记内容')).toHaveCount(0);
  await page.getByRole('button', { name: '阅读笔记', exact: true }).click();
  await expect(page.getByRole('complementary', { name: '阅读笔记' })).toContainText('未保存的阅读想法');
  await page.getByRole('button', { name: '编辑笔记' }).first().click();
  await page.getByLabel('笔记内容').fill('修改后的想法');
  await expect(page.getByRole('button', { name: '保存笔记', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await expect(page.getByRole('complementary', { name: '阅读笔记' })).toContainText('修改后的想法');
  await page.screenshot({ path: testInfo.outputPath('reading-notes-desktop.png') });
  notes = await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/notes`)).json();
  expect(notes.notes).toHaveLength(2); expect(notes.notes[0].reference.version).toBe(book.version);
});

test('追问固定原引用，独立讨论保留各层草稿，从管理会话和笔记返回来源', async ({ page, request }, testInfo) => {
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'discussion-book', title: '讨论验证', author: '', format: 'md', text: '# 本章\n\n讨论的固定原文。\n\n# 后章\n\n不同的下一页。' } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /讨论验证/u }).click();
  await page.getByRole('button', { name: '书伴', exact: true }).click();
  await expect(page.getByLabel('向书伴提问')).toBeEnabled();
  await page.getByLabel('向书伴提问').fill('解释这句'); await page.getByRole('button', { name: '发送给书伴' }).click();
  await expect(page.getByRole('button', { name: '继续追问', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '继续追问', exact: true }).click();
  await page.getByRole('button', { name: '下一页', exact: true }).click();
  await page.getByLabel('向书伴提问').fill('继续解释原句'); await page.getByRole('button', { name: '发送给书伴' }).click();
  await expect(page.locator('.reading-message')).toHaveCount(4);
  const root = await (await request.post(`${fakeApiRoot}/api/reading/books/${book.id}/companion`)).json();
  const history = await (await request.get(`${fakeApiRoot}/api/sessions/${root.sessionId}/session`)).json();
  expect(history.messages.filter((m: { role: string }) => m.role === 'user').at(-1).readingReference.text).toBe('讨论的固定原文。');
  await page.getByRole('button', { name: '存为阅读笔记' }).first().click();
  await expect(page.getByLabel('笔记内容')).toBeVisible(); await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await expect(page.getByLabel('笔记内容')).toHaveCount(0);
  await page.getByLabel('向书伴提问').fill('上层草稿');
  await page.getByRole('button', { name: '单独讨论', exact: true }).first().click();
  await expect(page.getByRole('button', { name: '返回上层讨论' })).toBeVisible();
  await expect(page.getByLabel('向书伴提问')).toHaveValue('');
  await page.getByLabel('向书伴提问').fill('子层草稿');
  const all = await (await request.get(`${fakeApiRoot}/api/reading/books/${book.id}/discussions`)).json();
  const child = all.discussions.find((d: { parentSessionId: string }) => d.parentSessionId === root.sessionId);
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/sessions/${child.sessionId}/page-state`)).json()).draft).toBe('子层草稿');
  await page.getByRole('button', { name: '返回上层讨论' }).click(); await expect(page.getByLabel('向书伴提问')).toHaveValue('上层草稿');
  await page.getByRole('button', { name: '阅读笔记', exact: true }).click();
  await page.getByRole('button', { name: '编辑笔记' }).click(); await page.getByRole('button', { name: '返回来源讨论' }).click();
  await expect(page.getByLabel('向书伴提问')).toHaveValue('上层草稿');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '会话', exact: true }).click();
  const row = page.locator('.reading-conversations tr').filter({ hasText: '讨论验证 · 独立讨论' });
  await row.getByRole('button').click();
  await expect(page.getByLabel('向书伴提问')).toHaveValue('子层草稿');
  await page.screenshot({ path: testInfo.outputPath('reading-discussion-desktop.png') });
  await page.reload(); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await expect(page.getByLabel('向书伴提问')).toHaveValue('子层草稿');
});

test('摘录真实收进目标笔记，定位来源并交接到 Multivac 引用草稿', async ({ page, request }, testInfo) => {
  const book = await (await request.post(`${fakeApiRoot}/api/reading/books`, { data: { commandId: 'collection-book', title: '收集交接验证', author: '', format: 'txt', text: '值得收集和交接的原文。' } })).json();
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '读书', exact: true }).click();
  await page.getByRole('navigation', { name: '书架' }).getByRole('button', { name: /收集交接验证/u }).click();
  await expect(page.locator('.reading-toolbar h2')).toHaveText('收集交接验证');
  await expect(page.locator('.reading-flow p span').first()).toBeVisible();
  const select = () => page.evaluate(() => {
    const span = document.querySelector('.reading-flow p span')!;
    const range = document.createRange(); range.selectNodeContents(span);
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range); document.dispatchEvent(new Event('selectionchange'));
  });
  await select(); await page.getByRole('button', { name: '收进笔记', exact: true }).click();
  const card = page.getByRole('dialog', { name: '收进笔记', exact: true });
  await expect(card.getByRole('button', { name: '收集', exact: true })).toBeEnabled(); await card.getByRole('button', { name: '收集', exact: true }).click();
  await page.getByRole('dialog', { name: '已收进笔记', exact: true }).getByRole('button', { name: '查看笔记' }).click();
  await expect(page.locator('.reading-collected-item')).toContainText('值得收集和交接的原文。');
  const items = await (await request.get(`${fakeApiRoot}/api/reading/collections?targetId=reading-inbox`)).json();
  expect(items.items.find((i: { reference: { bookId: string } }) => i.reference.bookId === book.id).reference.version).toBe(book.version);
  await page.getByRole('button', { name: '新建目标', exact: true }).click(); await page.getByLabel('目标名称').fill('独立读书摘录'); await page.getByRole('dialog', { name: '新建笔记接收目标' }).getByRole('button', { name: '创建', exact: true }).click();
  await expect(page.getByRole('navigation', { name: '笔记接收目标' }).getByRole('button', { name: '独立读书摘录' })).toBeVisible();
  await page.getByRole('navigation', { name: '笔记接收目标' }).getByRole('button', { name: '收集箱', exact: true }).click();
  await page.getByRole('button', { name: '定位书籍原文', exact: true }).click();
  await expect(page.locator('.reading-toolbar h2')).toHaveText('收集交接验证');
  await expect(page.locator('.reading-flow p span').first()).toBeVisible();
  await expect(page.getByRole('button', { name: '返回阅读处', exact: true })).toBeVisible();
  await select(); await page.getByRole('button', { name: '交给 Multivac', exact: true }).click();
  const sidebar = page.locator('.multivac-sidebar');
  await expect(sidebar).toBeVisible(); await expect(sidebar.locator('.composer-quote')).toContainText('值得收集和交接的原文。');
  await sidebar.getByLabel('Multivac 草稿').fill('围绕这段原文安排下一步');
  await sidebar.getByLabel('发送消息').click();
  await expect(sidebar.getByRole('status').getByText('处理完成', { exact: true })).toBeVisible();
  const history = await (await request.get(`${fakeApiRoot}/api/assistant/session`)).json();
  const user = history.messages.filter((m: { role: string }) => m.role === 'user').at(-1);
  expect(user.quote.sourceKind).toBe('book'); expect(user.quote.sourceBook.bookId).toBe(book.id);
  expect(user.quote.text).toBe('值得收集和交接的原文。');
  await page.screenshot({ path: testInfo.outputPath('reading-handoff-desktop.png') });
});
