import { expect, test } from '@playwright/test';
import { fakeApiRoot, openPanel, resetE2eState } from './test-state.js';

test('帮助四项操作与键盘一致，面板共用样式且 Esc 只处理顶层', async ({ page, request }) => {
  await resetE2eState(request);
  await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId: 'help-session', title: '快捷键会话' } });
  await page.goto('/');
  const help = page.getByRole('dialog', { name: '快捷键' });
  const trigger = page.getByRole('button', { name: '快捷键', exact: true });
  await trigger.click();
  await expect(help.getByRole('button')).toHaveCount(4);
  await expect(help.getByRole('button', { name: /快速跳转/ })).toBeDisabled();
  await expect(help.getByRole('button', { name: /工作区侧栏/ })).toBeDisabled();
  await help.getByRole('button', { name: /面板跳转/ }).click();
  const panel = page.getByRole('dialog', { name: '面板跳转' });
  await expect(panel).toHaveClass(/palette/);
  await page.screenshot({ path: 'test-results/panel-switcher.png' });
  await page.keyboard.press('2');
  await trigger.click();
  await page.screenshot({ path: 'test-results/shortcut-help.png' });
  await help.getByRole('button', { name: /快速跳转/ }).click();
  await expect(page.getByRole('dialog', { name: '跳到会话' })).toHaveClass(/palette/);
  await page.keyboard.press('ControlOrMeta+G');
  await expect(panel).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await trigger.click();
  await help.getByRole('button', { name: /工作区侧栏/ }).click();
  await expect(page.getByRole('complementary', { name: '工作区会话导航' })).toBeHidden();
  await page.keyboard.press('ControlOrMeta+B');
  await expect(page.getByRole('complementary', { name: '工作区会话导航' })).toBeVisible();
  await page.keyboard.press('ControlOrMeta+J');
  await trigger.click();
  await page.keyboard.press('Escape');
  await expect(help).toHaveCount(0);
  await expect(page.locator('.multivac-sidebar')).toBeVisible();
  await openPanel(page, 'management');
  await trigger.click();
  await expect(help.getByRole('button', { name: /快速跳转/ })).toBeEnabled();
  await expect(help.getByRole('button', { name: /工作区侧栏/ })).toBeDisabled();
});
