import { test, expect } from '@playwright/test';
import { fakeApiRoot, resetE2eState, openPanel } from './test-state.js';

test('任务筛选菜单支持键盘、关闭与焦点恢复，筛选移除选中详情', async ({ page, request }, testInfo) => {
  await resetE2eState(request);
  const projectName = '用于检查筛选菜单截断与换行的长项目名称';
  const workspace = (await (await request.post(`${fakeApiRoot}/api/projects`, { data: { name: projectName } })).json()).workspace;
  for (const [title, projectId] of [['项目任务', workspace.project.projectId], ['日常任务', null]]) {
    expect((await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title, goal: '检查菜单与真实任务筛选', projectId } })).ok()).toBeTruthy();
  }
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await expect(page.getByRole('button', { name: '任务看板', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.task-board-column')).toHaveCount(6);
  await page.getByRole('button', { name: '查看任务：项目任务', exact: true }).click();
  const project = page.getByRole('button', { name: '任务项目筛选：全部项目', exact: true });
  await project.focus();
  await page.keyboard.press('ArrowDown');
  const menu = page.getByRole('listbox', { name: '任务项目筛选', exact: true });
  await expect(menu.getByRole('option', { name: '全部项目', exact: true })).toBeFocused();
  await page.keyboard.press('End');
  await expect(menu.getByRole('option', { name: '日常', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(menu).toHaveCount(0);
  await expect(page.getByRole('button', { name: '任务项目筛选：日常', exact: true })).toBeFocused();
  await expect(page.getByRole('complementary', { name: '任务详情' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '查看任务：项目任务', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '查看任务：日常任务', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '任务项目筛选：日常', exact: true }).click();
  await menu.getByRole('option', { name: projectName, exact: true }).click();
  await expect(page.getByRole('button', { name: '查看任务：项目任务', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /^任务状态筛选/ })).toHaveCount(0);
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  const status = page.getByRole('button', { name: '任务状态筛选：全部状态', exact: true });
  await status.click();
  await expect(page.getByRole('listbox', { name: '任务状态筛选', exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('task-filters-1440.png'), animations: 'disabled' });
  await page.keyboard.press('Escape');
  await expect(status).toBeFocused();
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await status.click();
  await page.getByRole('textbox', { name: '搜索任务', exact: true }).click();
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await status.click();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: '任务看板', exact: true })).toBeFocused();
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await page.setViewportSize({ width: 900, height: 820 });
  await status.click();
  const bounds = await page.getByRole('listbox').boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(900);
  await page.screenshot({ path: testInfo.outputPath('task-filters-900.png'), animations: 'disabled' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '查看任务：项目任务', exact: true }).click();
  const inspector = page.getByRole('complementary', { name: '任务详情' });
  await expect(inspector).toBeVisible();
  expect(await inspector.evaluate((element) => getComputedStyle(element).position)).toBe('absolute');
  expect(await inspector.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await inspector.getByRole('button', { name: '关闭任务详情' }).click();
  await expect(inspector).toHaveCount(0);
});

test('暂停任务保留看板列和状态筛选，实时取消后清除隐藏详情', async ({ page, request }) => {
  await resetE2eState(request);
  let task = (await (await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title: '可暂停任务', goal: '验证真实暂停状态' } })).json()).task;
  expect((await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: task.revision, action: 'start' } })).ok()).toBeTruthy();
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/tasks/${task.taskId}`)).json()).task.status).toBe('waiting');
  task = (await (await request.get(`${fakeApiRoot}/api/tasks/${task.taskId}`)).json()).task;
  const pause = await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: task.revision, action: 'pause' } });
  expect(pause.ok()).toBeTruthy();
  task = (await pause.json()).task;
  expect(task.status).toBe('paused');
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await expect(page.locator('[data-column="paused"]')).toContainText('可暂停任务');
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await page.getByRole('button', { name: '任务状态筛选：全部状态', exact: true }).click();
  await page.getByRole('option', { name: '已暂停', exact: true }).click();
  await page.getByRole('button', { name: '查看任务：可暂停任务', exact: true }).click();
  await expect(page.getByRole('complementary', { name: '任务详情' })).toBeVisible();
  expect((await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: task.revision, action: 'cancel' } })).ok()).toBeTruthy();
  await expect(page.getByRole('complementary', { name: '任务详情' })).toHaveCount(0);
  await expect(page.locator('[data-column="paused"]')).toHaveCount(0);
  await expect(page.getByText('没有符合筛选条件的任务', { exact: true })).toBeVisible();
});

test('列表状态独立于看板，切换保留项目搜索和仍可见的详情', async ({ page, request }) => {
  await resetE2eState(request);
  for (const title of ['范围内未开始', '范围内已取消']) {
    const task = (await (await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title, goal: title } })).json()).task;
    if (title.endsWith('已取消')) expect((await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: task.revision, action: 'cancel' } })).ok()).toBeTruthy();
  }
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await page.getByRole('textbox', { name: '搜索任务', exact: true }).fill('范围内');
  await page.getByRole('button', { name: '任务项目筛选：全部项目', exact: true }).click();
  await page.getByRole('option', { name: '日常', exact: true }).click();
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await page.getByRole('button', { name: '任务状态筛选：全部状态', exact: true }).click();
  await page.getByRole('option', { name: '已取消', exact: true }).click();
  await expect(page.getByLabel('任务数量')).toHaveText('当前显示 1 / 1 个任务');
  await page.getByRole('button', { name: '查看任务：范围内已取消', exact: true }).click();
  const inspector = page.getByRole('complementary', { name: '任务详情' });
  await expect(inspector).toBeVisible();
  const boardRead = page.waitForResponse((response) => {
    const url = new URL(response.url());
    return url.pathname === '/api/tasks' && url.searchParams.get('query') === '范围内' && url.searchParams.get('projectId') === 'daily' && !url.searchParams.has('viewStatus');
  });
  await page.getByRole('button', { name: '任务看板', exact: true }).click();
  expect((await boardRead).ok()).toBeTruthy();
  await expect(page.getByRole('button', { name: /^任务状态筛选/ })).toHaveCount(0);
  await expect(page.locator('[data-column="idle"]')).toContainText('范围内未开始');
  await expect(page.locator('[data-column="cancelled"]')).toContainText('范围内已取消');
  await expect(inspector).toBeVisible();
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await expect(page.getByRole('button', { name: '任务状态筛选：已取消', exact: true })).toBeVisible();
  await expect(page.getByLabel('任务数量')).toHaveText('当前显示 1 / 1 个任务');
  await expect(page.getByRole('button', { name: '查看任务：范围内未开始', exact: true })).toHaveCount(0);
  await expect(inspector).toBeVisible();
  await expect(page.getByRole('textbox', { name: '搜索任务', exact: true })).toHaveValue('范围内');
  await expect(page.getByRole('button', { name: '任务项目筛选：日常', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '任务看板', exact: true }).click();
  await page.getByRole('button', { name: '查看任务：范围内未开始', exact: true }).click();
  await expect(inspector).toContainText('范围内未开始');
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await expect(inspector).toHaveCount(0);
});
