import { test, expect } from '@playwright/test';
import { fakeApiRoot, openPanel, resetE2eState } from './test-state.js';

test('概览精简关系并保留排队等待，详情保留长目标与完整进展，更多操作支持 Esc 返回焦点', async ({ page, request }, testInfo) => {
  await resetE2eState(request);
  const create = async (title: string, fields = {}) => (await (await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title, goal: title, ...fields } })).json()).task;
  const parent = await create('上线账号功能');
  const dependency = await create('准备登录接口');
  let child = await create('联调登录流程', { parentTaskId: parent.taskId, dependencyIds: [dependency.taskId], goal: '验证登录成功和失败的处理。'.repeat(35) });
  for (let i = 0; i < 6; i++) child = (await (await request.patch(`${fakeApiRoot}/api/tasks/${child.taskId}`, { data: { commandId: crypto.randomUUID(), revision: child.revision, patch: { scope: `参考资料 ${i}` } } })).json()).task;
  await page.goto('/'); await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  const card = page.locator(`.task-board-card[data-task-id="${child.taskId}"]`);
  await expect(card).not.toContainText('准备登录接口');
  await expect(card).not.toContainText('上线账号功能');
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await expect(page.locator('.task-tree-parent')).toHaveCount(0);
  await page.getByRole('textbox', { name: '搜索任务', exact: true }).fill(child.title);
  await expect(page.locator('.task-tree-parent')).toContainText(parent.title);
  await expect(page.locator('.task-list-row')).not.toContainText('准备登录接口');
  await page.getByRole('textbox', { name: '搜索任务', exact: true }).fill('');
  await page.getByRole('button', { name: '任务看板', exact: true }).click();
  await expect(card).not.toContainText('已取消 0');
  await card.getByRole('button', { name: `查看任务：${child.title}`, exact: true }).click();
  const inspector = page.getByRole('complementary', { name: '任务详情' });
  await expect(inspector.locator('.task-events li')).toHaveCount(4);
  await expect(inspector.getByText('暂无成果', { exact: true })).toHaveCount(0);
  await expect(inspector.getByText(child.taskId, { exact: true })).toHaveCount(0);
  await inspector.getByRole('button', { name: '展开目标', exact: true }).click();
  await expect(inspector.locator('.task-goal')).not.toHaveClass(/collapsed/);
  await inspector.getByRole('button', { name: '查看全部进展', exact: true }).click();
  await expect(inspector.locator('.task-events li')).toHaveCount(7);
  await inspector.getByRole('button', { name: '收起进展', exact: true }).click();
  await expect(inspector.locator('.task-events li')).toHaveCount(4);
  await expect(inspector.getByRole('button', { name: `删除任务：${child.title}` })).toHaveCount(0);
  const more = inspector.getByRole('button', { name: '更多任务操作', exact: true });
  await more.click(); await page.keyboard.press('Escape');
  await expect(more).toBeFocused(); await expect(more).toHaveAttribute('aria-expanded', 'false');
  await expect(inspector).toBeVisible();
  await inspector.getByRole('button', { name: '收起目标', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('task-density-wide.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 900, height: 760 });
  await expect(inspector).toBeVisible();
  expect(await inspector.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('task-density-narrow.png'), animations: 'disabled' });
  const queued = await request.post(`${fakeApiRoot}/api/tasks/${child.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: child.revision, action: 'start' } });
  expect(queued.ok()).toBeTruthy();
  await expect(card.getByText('等待「准备登录接口」完成', { exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: '关闭任务详情', exact: true }).click();
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  await expect(page.locator('.task-list-row').filter({ hasText: child.title })).toContainText('等待「准备登录接口」完成');
  const current = (await (await request.get(`${fakeApiRoot}/api/tasks/${child.taskId}`)).json()).task;
  const cancelled = await request.post(`${fakeApiRoot}/api/tasks/${child.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: current.revision, action: 'cancel' } });
  expect(cancelled.ok()).toBeTruthy();
  await expect.poll(async () => (await (await request.get(`${fakeApiRoot}/api/tasks/${child.taskId}`)).json()).runs[0].stopConfirmed).toBe(true);
});
