import { test, expect } from '@playwright/test';
import { fakeApiRoot, resetE2eState, openPanel } from './test-state.js';

test('看板与列表仅在详情删除，删除需确认，失败可重试，其他窗口同步移除并清除详情', async ({ page, context, request }) => {
  await resetE2eState(request);
  const create = async (title: string) => (await (await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title, goal: title } })).json()).task;
  const first = await create('待删除任务');
  const second = await create('列表删除任务');
  await page.goto('/');
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  const other = await context.newPage();
  await other.goto('/');
  await openPanel(other, 'management');
  await other.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await other.getByRole('button', { name: '查看任务：待删除任务', exact: true }).click();
  const card = page.locator('.task-board-card').filter({ hasText: '待删除任务' });
  const start = card.getByRole('button', { name: '启动任务：待删除任务', exact: true });
  await expect(start).toHaveAttribute('title', '启动任务');
  await expect(card.getByRole('button', { name: '删除任务：待删除任务', exact: true })).toHaveCount(0);
  await card.getByRole('button', { name: '查看任务：待删除任务', exact: true }).click();
  await page.getByRole('button', { name: '更多任务操作', exact: true }).click();
  await page.getByRole('complementary', { name: '任务详情' }).getByRole('button', { name: '删除任务：待删除任务', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: '删除「待删除任务」', exact: true });
  await expect(confirmation.getByRole('button', { name: '取消', exact: true })).toBeFocused();
  await confirmation.getByRole('button', { name: '取消', exact: true }).click();
  await expect(card).toBeVisible();
  expect((await request.get(`${fakeApiRoot}/api/tasks/${first.taskId}`)).ok()).toBeTruthy();
  let fail = true;
  await page.route(`**/api/tasks/${first.taskId}`, async (route) => {
    if (route.request().method() === 'DELETE' && fail) {
      fail = false;
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'INTERNAL_ERROR', message: '删除失败，请重试。' } }) });
    } else await route.continue();
  });
  await expect(card.getByRole('button', { name: '删除任务：待删除任务', exact: true })).toHaveCount(0);
  await card.getByRole('button', { name: '查看任务：待删除任务', exact: true }).click();
  await page.getByRole('button', { name: '更多任务操作', exact: true }).click();
  await page.getByRole('complementary', { name: '任务详情' }).getByRole('button', { name: '删除任务：待删除任务', exact: true }).click();
  await confirmation.getByRole('button', { name: '删除任务', exact: true }).click();
  await expect(confirmation.getByRole('alert')).toContainText('删除失败');
  await expect(card).toBeVisible();
  await confirmation.getByRole('button', { name: '删除任务', exact: true }).click();
  await expect(confirmation).toHaveCount(0);
  await expect(card).toHaveCount(0);
  await expect(other.getByRole('complementary', { name: '任务详情' })).toHaveCount(0);
  await expect(other.getByRole('button', { name: '查看任务：待删除任务', exact: true })).toHaveCount(0);
  expect((await request.get(`${fakeApiRoot}/api/tasks/${first.taskId}`)).status()).toBe(404);
  await page.getByRole('button', { name: '任务列表', exact: true }).click();
  const row = page.locator('.task-list-row').filter({ hasText: '列表删除任务' });
  await expect(row.getByRole('button', { name: '删除任务：列表删除任务', exact: true })).toHaveCount(0);
  await row.getByRole('button', { name: '查看任务：列表删除任务', exact: true }).click();
  await page.getByRole('button', { name: '更多任务操作', exact: true }).click();
  await page.getByRole('complementary', { name: '任务详情' }).getByRole('button', { name: '删除任务：列表删除任务', exact: true }).click();
  await page.getByRole('dialog', { name: '删除「列表删除任务」', exact: true }).getByRole('button', { name: '删除任务', exact: true }).click();
  await expect(row).toHaveCount(0);
  expect((await request.get(`${fakeApiRoot}/api/tasks/${second.taskId}`)).status()).toBe(404);
  await page.reload();
  await openPanel(page, 'management');
  await page.getByRole('complementary', { name: '管理导航' }).getByRole('button', { name: '待办', exact: true }).click();
  await expect(page.getByText('没有符合筛选条件的任务', { exact: true })).toBeVisible();
  expect((await (await request.get(`${fakeApiRoot}/api/tasks`)).json()).total).toBe(0);
});
