import { test, expect } from '@playwright/test';
import { fakeApiRoot, resetE2eState, openPanel } from './test-state.js';

test('任务与已有会话互跳保留请求草稿，成果取消后仍可读取，不显示未接入的独立页面', async ({ page, request }, testInfo) => {
  await resetE2eState(request);
  const title = `核对来源 ${Date.now()}`;
  let task = (await (await request.post(`${fakeApiRoot}/api/tasks`, { data: { commandId: crypto.randomUUID(), title, goal: '核对两份资料的依据', acceptance: true } })).json()).task;
  const detail = async () => (await (await request.get(`${fakeApiRoot}/api/tasks/${task.taskId}`)).json());
  await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/control`, { data: { commandId: crypto.randomUUID(), revision: task.revision, action: 'start' } });
  await expect.poll(async () => (await detail()).task.status).toBe('waiting');
  task = (await detail()).task;
  const input = await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/requests`, { data: { commandId: crypto.randomUUID(), question: '需要采用哪份资料？' } });
  expect(input.ok()).toBe(true);
  await page.goto('/');
  await openPanel(page, 'management');
  const nav = page.getByRole('complementary', { name: '管理导航' });
  await expect(nav.getByRole('button', { name: '运行', exact: true })).toHaveCount(0);
  await expect(nav.getByRole('button', { name: '收件箱', exact: true })).toHaveCount(0);
  await expect(nav.getByRole('button', { name: '成果', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: `查看任务：${title}`, exact: true }).click();
  const inspector = page.getByRole('complementary', { name: '任务详情' });
  await inspector.getByLabel('澄清回应').fill('保留原文及发布日期，先比较差异');
  await inspector.getByRole('button', { name: `打开任务会话：${title}` }).click();
  const work = page.locator('.session-task-link').filter({ hasText: title });
  await expect(work).toBeVisible();
  const sessionCard = page.locator('.workspace-page .task-request-card');
  await expect(sessionCard.getByLabel('澄清回应')).toHaveValue('保留原文及发布日期，先比较差异');
  await work.getByRole('button', { name: title, exact: true }).click();
  await expect(inspector.getByLabel('澄清回应')).toHaveValue('保留原文及发布日期，先比较差异');
  await page.keyboard.press('ControlOrMeta+J');
  const sidebar = page.locator('.multivac-sidebar');
  const sent = page.waitForRequest((item) => item.method() === 'POST' && new URL(item.url()).pathname === '/api/assistant/turns');
  await sidebar.getByLabel('Multivac 草稿').fill('这个任务的当前情况\n内部工具：get_current_view#task-current-view {}');
  await sidebar.getByLabel('发送消息').click();
  const payload = (await sent).postDataJSON();
  expect(payload.view.management.selection).toEqual({ kind: 'task', taskId: task.taskId });
  expect(payload.contextRefs).toEqual([{ kind: 'task', taskId: task.taskId }]);
  await expect(sidebar.getByRole('status').getByText('处理完成', { exact: true })).toBeVisible();
  await page.keyboard.press('ControlOrMeta+J');
  await page.screenshot({ path: testInfo.outputPath('task-request-1440.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 1120, height: 820 });
  await page.screenshot({ path: testInfo.outputPath('task-request-1120.png'), fullPage: true, animations: 'disabled' });
  await inspector.getByRole('button', { name: '不采用', exact: true }).click();
  await expect(inspector.getByLabel('澄清回应')).toHaveCount(0);
  await expect.poll(async () => (await detail()).runs[0]?.stopConfirmed).toBe(true);
  task = (await detail()).task;
  const result = await request.post(`${fakeApiRoot}/api/tasks/${task.taskId}/artifacts`, { data: { commandId: crypto.randomUUID(), revision: task.revision, runId: task.currentRunId, title: '来源核对记录', text: '## 核对结果\n保留原文与发布日期，差异尚待用户判断。' } });
  expect(result.ok()).toBe(true);
  const version = (await result.json()).version;
  await expect(inspector).toContainText('来源核对记录');
  await inspector.getByRole('button', { name: `取消任务：${title}` }).click();
  await expect(inspector).toContainText('已取消');
  await inspector.locator('.task-output-link').click();
  await expect(inspector.locator('.task-artifact-preview')).toContainText('差异尚待用户判断');
  expect((await (await request.get(`${fakeApiRoot}/api/artifacts/${version.versionId}`)).json()).version.versionId).toBe(version.versionId);
  await page.screenshot({ path: testInfo.outputPath('task-artifact-1120.png'), fullPage: true, animations: 'disabled' });
  await expect(page.getByRole('heading', { name: '待办', exact: true })).toBeVisible();
  const layout = await page.locator('.task-panel-layout').evaluate((element) => {
    const main = element.querySelector('.task-panel-main')!.getBoundingClientRect();
    const pane = element.querySelector('.task-inspector')!;
    return { right: main.right, left: pane.getBoundingClientRect().left, layoutRight: element.getBoundingClientRect().right, layoutLeft: element.getBoundingClientRect().left, paneRight: pane.getBoundingClientRect().right, overlay: getComputedStyle(pane).position === 'absolute', overflow: pane.scrollWidth > pane.clientWidth };
  });
  if (layout.overlay) {
    expect(layout.left).toBeGreaterThanOrEqual(layout.layoutLeft);
    expect(layout.paneRight).toBeLessThanOrEqual(layout.layoutRight + 1);
  }
  else expect(layout.right).toBeLessThanOrEqual(layout.left + 1);
  expect(layout.overflow).toBe(false);
  await inspector.getByRole('button', { name: `删除任务：${title}`, exact: true }).click();
  await page.getByRole('dialog', { name: `删除「${title}」`, exact: true }).getByRole('button', { name: '删除任务', exact: true }).click();
  await expect(inspector).toHaveCount(0);
  expect((await request.get(`${fakeApiRoot}/api/tasks/${task.taskId}`)).status()).toBe(404);
  expect((await (await request.get(`${fakeApiRoot}/api/artifacts/${version.versionId}`)).json()).version.versionId).toBe(version.versionId);
  const sessions = (await (await request.get(`${fakeApiRoot}/api/sessions`)).json()).sessions;
  expect(sessions.some((session: { sessionId: string }) => session.sessionId === task.sessionId)).toBe(true);

});
