import { expect, test } from '@playwright/test';
import { fakeApiRoot, openPanel, resetE2eState } from './test-state.js';

test('侧栏按可读空间停靠或浮层，布局与开合偏好各自保持', async ({ page, request }) => {
  await resetE2eState(request);
  for (let n = 1; n <= 4; n++) expect((await request.post(`${fakeApiRoot}/api/sessions`, { data: { sessionId: `rail-${n}`, title: `阅读 ${n}` } })).ok()).toBe(true);
  await page.goto('/');
  await openPanel(page, 'workspace');
  const rail = page.getByRole('complementary', { name: '工作区会话导航' });
  await expect(rail).toBeVisible();
  await rail.getByRole('radio', { name: '并排 4 栏' }).click();
  await expect(page.locator('.workspace-rail-wrap.overlay')).toBeVisible();
  await expect(page.locator('.conversation-panel')).toHaveCount(4);
  await page.screenshot({ path: 'test-results/workspace-rail-overlay.png' });
  await rail.locator('[data-workspace-id="default"]').getByRole('button', { name: '阅读 1', exact: true }).click();
  await expect(rail).toBeHidden();
  await page.keyboard.press('ControlOrMeta+B');
  await expect(rail).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(rail).toBeHidden();
  await page.keyboard.press('ControlOrMeta+B');
  await rail.getByRole('radio', { name: '聚焦：只看当前会话' }).click();
  await expect(page.locator('.workspace-rail-wrap.overlay')).toHaveCount(0);
  await expect(rail).toBeVisible();
  await expect(page.locator('.conversation-panel')).toHaveCount(1);
  await page.keyboard.press('ControlOrMeta+B');
  await expect(rail).toBeHidden();
  await page.reload();
  await openPanel(page, 'workspace');
  await expect(rail).toBeHidden();
  await page.getByRole('button', { name: '展开工作区侧栏' }).click();
  await expect(rail).toBeVisible();
  await rail.getByRole('radio', { name: '并排 3 栏' }).click();
  await page.keyboard.press('ControlOrMeta+J');
  await expect(rail).toBeHidden();
  await page.keyboard.press('ControlOrMeta+B');
  await expect(page.locator('.workspace-rail-wrap.overlay')).toBeVisible();
  await page.locator('.conversation-panel').last().locator('h2').click();
  await expect(rail).toBeHidden();
});
