import { mkdir } from 'node:fs/promises';
await mkdir('.tmp/prototype-alignment', { recursive: true });
import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({headless: true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror', error=>errors.push(error.message));
async function nav(label) { await page.locator('.sidebar').getByRole('button',{name:label,exact:true}).click(); }
try {
  await page.goto(process.env.PROTOTYPE_URL || 'http://127.0.0.1:5179');
  await page.getByText('下午好。',{exact:false}).waitFor();
  await page.keyboard.press('Meta+g');
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('3');
  await expect(page.getByRole('heading',{name:'待办',exact:true})).toBeVisible();
  await expect(page.getByRole('region',{name:'已暂停',exact:true})).toBeVisible();
  await page.screenshot({path:'.tmp/prototype-alignment/tasks.png'});
  await page.getByRole('button',{name:'创建任务',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.locator('input[required]').fill('人工前置');
  await dialog.locator('textarea').fill('确认资料完整');
  await dialog.getByLabel('我来处理',{exact:true}).check();
  await dialog.getByRole('button',{name:'创建任务',exact:true}).click();
  const inspector=page.getByRole('complementary',{name:'任务详情'});
  await expect(inspector.getByRole('heading',{name:'人工前置',exact:true})).toBeVisible();
  await expect(inspector.getByText('无需 Agent 执行目录',{exact:true})).toBeHidden();
  await inspector.getByRole('button',{name:'创建子任务',exact:true}).click();
  await dialog.locator('input[required]').fill('等待前置的子任务');
  await dialog.locator('textarea').fill('前置完成之后执行');
  await dialog.getByLabel('人工前置',{exact:true}).check();
  await dialog.getByRole('button',{name:'创建任务',exact:true}).click();
  await expect(inspector.getByRole('heading',{name:'等待前置的子任务',exact:true})).toBeVisible();
  await inspector.getByRole('button',{name:'启动',exact:true}).click();
  await expect(inspector.getByText('排队中',{exact:true})).toBeVisible();
  await page.screenshot({path:'.tmp/prototype-alignment/dependencies.png'});
  await inspector.getByRole('button',{name:/人工前置.*未开始/}).first().click();
  await inspector.getByRole('button',{name:'标记完成',exact:true}).click();
  await expect(inspector.getByText('你已确认处理完成',{exact:true}).first()).toBeVisible();
  await inspector.getByRole('button',{name:/等待前置的子任务.*执行中/}).click();
  await expect(inspector.getByText('前置条件已满足，开始执行',{exact:true}).first()).toBeVisible();
  await page.getByRole('button',{name:'关闭任务详情',exact:true}).click();
  await page.getByRole('button',{name:'列表视图',exact:true}).click();
  await page.getByRole('textbox',{name:'搜索任务',exact:true}).fill('资料');
  await nav('项目');
  await nav('待办');
  await expect(page.getByRole('textbox',{name:'搜索任务',exact:true})).toHaveValue('资料');
  await page.getByRole('textbox',{name:'搜索任务',exact:true}).fill('');
  await page.getByRole('button',{name:'查看任务：审阅实现结果',exact:true}).click();
  await expect(inspector.getByRole('button',{name:'接受成果',exact:true})).toBeVisible();
  await page.screenshot({path:'.tmp/prototype-alignment/review.png'});
  await inspector.getByRole('button',{name:'接受成果',exact:true}).click();
  await expect(inspector.getByText('已完成',{exact:true})).toBeVisible();
  await nav('偏好');
  const retention=page.getByRole('combobox',{name:'临时目录清理',exact:true});
  await expect(retention).toHaveValue('30');
  await retention.selectOption('never');
  await nav('会话');
  const sessionList=page.getByRole('region',{name:'会话列表'});
  await sessionList.getByRole('button').first().click();
  await page.getByRole('button',{name:'归档',exact:true}).filter({has:page.locator('svg')}).last().click();
  if(await page.getByRole('dialog',{name:'归档前确认'}).isVisible()) await page.getByRole('button',{name:'直接归档',exact:true}).click();
  await nav('归档');
  await expect(page.getByRole('button',{name:'恢复并打开',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'恢复',exact:true}).click();
  await expect(page.getByRole('button',{name:'继续在工作区打开',exact:true})).toBeVisible();
  await page.screenshot({path:'.tmp/prototype-alignment/archive.png'});
  await nav('读书');
  await expect(page.getByRole('heading',{name:'《数据密集型应用系统设计》',exact:true})).toBeVisible();
  console.log(JSON.stringify({passed:true,errors}));
  expect(errors).toEqual([]);
} catch(error) {
  console.log('ERRORS',errors);
  console.log((await page.locator('body').innerText()).slice(-8000));
  await page.screenshot({path:'.tmp/prototype-alignment/failure.png'});
  throw error;
} finally { await browser.close(); }
