import { useEffect, useLayoutEffect, useRef, useState, type RefObject } from 'react';
import { ArrowLeft, Pencil, Save, Trash2, X, MoreHorizontal } from 'lucide-react';
import { positionRank, validBookReference, type Book, type BookReference, type ReadingNoteDraft, type ReadingNote } from '@multivac/contracts';
import type { useReadingNotes } from './use-reading-notes.js';
import { useReadingFloating, ReadingActionsMenu } from './reading-floating.js';

export function noteDraft(note: ReadingNoteDraft): ReadingNoteDraft {
  return { id: note.id, body: note.body, reference: note.reference, origin: note.origin, ...(note.discussion ? { discussion: note.discussion } : {}) };
}
export function ReadingNotesPanel({ root, book, pageReference, notes, locate, edit, handover }: { root: RefObject<HTMLElement | null>; book: Book; pageReference: BookReference | null; notes: ReturnType<typeof useReadingNotes>; locate: (r: BookReference) => void; edit: (draft: ReadingNoteDraft) => void; handover: (note: ReadingNote) => void }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [menu, setMenu] = useState<{ anchor: HTMLElement; note: ReadingNote } | null>(null);
  const sorted = [...notes.state.notes].sort((a,b) => (validBookReference(book,a.reference) ? positionRank(book,a.reference.start) : Infinity) - (validBookReference(book,b.reference) ? positionRank(book,b.reference.start) : Infinity));
  return <aside className="reading-record-panel reading-notes-list" aria-label="阅读笔记">{notes.draft && <button className="reading-resume-note reading-tool" onClick={() => edit(notes.draft!)}><i className="reading-draft-dot" />继续草稿<Pencil size={13} /></button>}
    {!notes.state.notes.length && <div className="reading-notes-empty"><Pencil size={25} /><strong>暂无阅读笔记</strong><button className="reading-tool" disabled={!pageReference} onClick={() => pageReference && edit({ id: crypto.randomUUID(), body: '', reference: pageReference, origin: 'user' })}>记下第一条笔记</button></div>}
    {menu && <ReadingActionsMenu root={root} anchor={menu.anchor} close={() => setMenu(null)} label="阅读笔记更多操作" actions={[{ label: '交给 Multivac', run: () => handover(menu.note) }]} />}
    {sorted.map(note => <article key={note.id} className="reading-record"><div className="reading-note-meta"><button className="reading-note-location" title="定位笔记原文" aria-label="定位笔记原文" disabled={!validBookReference(book, note.reference)} onClick={() => locate(note.reference)}>{book.chapters.find(c => c.id === note.reference.start.chapterId)?.title || '原文位置不可用'}<ArrowLeft size={12} /></button>{pageReference && validBookReference(book, note.reference) && positionRank(book,note.reference.start) < positionRank(book,pageReference.end) && positionRank(book,note.reference.end) > positionRank(book,pageReference.start) && <small>本页</small>}</div><blockquote className={expanded.has(note.id) ? '' : 'reading-note-excerpt'}>{note.reference.text}</blockquote><p className={expanded.has(note.id) ? '' : 'reading-note-preview'}>{note.body}</p><div className="reading-record-actions"><button className="reading-tool" aria-expanded={expanded.has(note.id)} onClick={() => setExpanded(s => { const next = new Set(s); if (next.has(note.id)) next.delete(note.id); else next.add(note.id); return next; })}>{expanded.has(note.id) ? '收起' : '展开'}</button><small>{note.origin === 'companion' ? '来自书伴' : ''}{!validBookReference(book, note.reference) && ' · 原位置已失效'}</small><button className="reading-icon" title="编辑笔记" aria-label="编辑笔记" onClick={() => edit(noteDraft(note))}><Pencil size={14} /></button><button className="reading-icon" title="删除笔记" aria-label="删除笔记" disabled={notes.busy || Boolean(notes.pending)} onClick={() => void notes.deleteNote(note.id)}><Trash2 size={14} /></button><button className="reading-icon" title="笔记更多操作" aria-label="笔记更多操作" aria-haspopup="menu" onClick={event => setMenu({ anchor: event.currentTarget, note })}><MoreHorizontal size={14} /></button></div></article>)}
  </aside>;
}
export function ReadingNoteCard({ root, book, notes, edit, returnDiscussion, close, locate }: { root: RefObject<HTMLElement | null>; book: Book; notes: ReturnType<typeof useReadingNotes>; edit: (draft: ReadingNoteDraft) => void; returnDiscussion: (source: NonNullable<ReadingNoteDraft['discussion']>) => void; close: () => void; locate: (r: BookReference) => void }) {
  const textarea = useRef<HTMLTextAreaElement>(null);
  const floating = useReadingFloating(root, null, true);
  useEffect(() => { textarea.current?.focus(); }, [notes.draft?.id]);
  useLayoutEffect(() => { if (document.activeElement === textarea.current) textarea.current?.scrollIntoView({ block: 'nearest' }); }, [floating.style.maxHeight, floating.style.top]);
  if (!notes.draft) return null;
  const related = notes.state.notes.filter(n => n.reference.start.paragraphId === notes.draft!.reference.start.paragraphId);
  return <div {...floating} className="reading-note-card" role="dialog" aria-label="阅读笔记草稿" onKeyDown={event => { if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); close(); } }}><header><strong>{notes.target ? '处理未保存草稿' : '阅读笔记草稿'}</strong><button className="reading-command" title="收起笔记，保留草稿" aria-label="收起笔记，保留草稿" onClick={close}><X size={16} /></button></header>
    {notes.target && <div className="reading-draft-conflict"><p>已有未保存草稿。</p><button disabled={notes.busy} onClick={() => void notes.save(notes.target)}>保存并继续</button><button disabled={notes.busy} onClick={() => void notes.discard(notes.target)}>放弃并继续</button><button onClick={notes.continueDraft}>继续原草稿</button></div>}
    {notes.draft.discussion && <button className="reading-command" onClick={() => returnDiscussion(notes.draft!.discussion!)}><ArrowLeft size={16} />返回来源讨论</button>}
    {related.length > 1 && <label>此处笔记<select aria-label="选择此处笔记" value={notes.draft.id} onChange={event => { const note = related.find(n => n.id === event.target.value); if (note) edit(noteDraft(note)); }}><option value={notes.draft.id}>当前草稿</option>{related.filter(n => n.id !== notes.draft!.id).map(n => <option value={n.id} key={n.id}>{n.body.slice(0, 24)}</option>)}</select></label>}
    <blockquote>{notes.draft.reference.text}</blockquote>{!validBookReference(book, notes.draft.reference) && <small>原位置已失效 · 摘录已保留</small>}<textarea ref={textarea} aria-label="笔记内容" rows={6} maxLength={12000} disabled={notes.locked} value={notes.draft.body} onChange={event => notes.change({ ...notes.draft!, body: event.target.value })} />
    {notes.error && <div role="alert">{notes.error}<details><summary>服务端草稿</summary><p>{notes.state.draft?.body ?? '无草稿'}</p></details>{notes.pending && <button disabled={notes.busy} onClick={notes.retry}>重试原命令</button>}<button disabled={notes.busy} onClick={() => void notes.resolveLocal()}>核对后保留当前草稿</button></div>}
    <footer><small role="status">{notes.busy ? '正在保存' : JSON.stringify(notes.draft) === JSON.stringify(notes.state.draft) ? '草稿已保留' : '草稿待保存'}</small><button className="reading-command" title="定位草稿原文" aria-label="定位草稿原文" disabled={!validBookReference(book, notes.draft.reference)} onClick={() => locate(notes.draft!.reference)}><ArrowLeft size={16} /></button><button className="reading-command" disabled={notes.busy || Boolean(notes.pending) || !notes.draft.body.trim()} onClick={() => void notes.save()}><Save size={16} />保存笔记</button><button className="reading-command" title="放弃草稿" aria-label="放弃草稿" disabled={notes.busy || Boolean(notes.pending)} onClick={() => void notes.discard()}><Trash2 size={16} /></button></footer>
  </div>;
}
